### ISSUE TITLE
Customizable alarms per subscription

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#1]
- Support customizable alarms per subscription (for instance: add an alarm 10 min before the event for every event in the subscription)
  - [x] Create UI for setting per subscription: "Add custom alarm" (Edit calendar activity)
    - [x] Give multiple alarm [options](https://developer.android.com/reference/android/provider/CalendarContract.RemindersColumns) (see `METHOD_*`).
    - [x] Make sure the calendar [supports the selected option](https://developer.android.com/reference/android/provider/CalendarContract.CalendarColumns#ALLOWED_REMINDERS).
  - [x] Save setting per subscription: "Add custom alarm"
  - [x] Actually make this setting work
- Possibility to disable alarms which come with the .ics
  - [x] Create UI for setting per subscription: "Ignore alarms from file" (Edit calendar activity)
  - [x] Save setting per subscription: "Ignore alarms from file"
  - [x] Actually make this setting work

**Comment by lvpha** [comment]
We really need such feature to just set the default reminder for a calendar. Just like G Cal has. When subscribing to a school/job calendar with back to back events. It is very inconvenient to have a 1 hour before notification.

**Comment by Zocker1999NET** [comment]
Hey, would also like to have this feature. Would also like to see another (hopefully simple) mini feature: If reminders are configured to be ignored from the subscribed calendar, do not overwrite/change the reminders which were added/changed by the calendar app.
The idea came to me because Etar Calendar (the app I use), lets me to add or change reminders to events of read only calendars, however these will be reseted when ICSx5 refreshes the calendar. And when ignoring all reminders from the remote is enabled, ICSx5 knows for sure, that the reminders which are configured locally must be from the user.

**Comment by ilikenwf** [comment]
I too would like to see this feature, MS removed the export of notification reminders in their ics files, or at least they don't seem to consistently export them....seems that sometimes they are exported when manually set by the user, but the value set by the organizer usually doesn't trigger a reminder or something.

**Comment by ArnyminerZ** [comment]
A mock for the new UI

![Screenshot_20221202-012507](https://user-images.githubusercontent.com/12086466/205187177-5eb8d47e-9d71-451e-93fe-c1bf17ea0651.png)

**Comment by rfc2822** [comment]
Thanks; do you have an UI idea @devvv4ever?

I think we can reduce the UI to two settings (switches):

1. ignore Webcal alarms
2. add custom alarm: xx minutes before event

with as little text as possible

**Comment by ArnyminerZ** [comment]
> Thanks; do you have an UI idea @devvv4ever?
> 
> I think we can reduce the UI to two settings (switches):
> 
>     1. ignore Webcal alarms
> 
>     2. add custom alarm: xx minutes before event
> 
> 
> with as little text as possible

Okay, I can simplify it 😉

**Comment by ArnyminerZ** [comment]
New UI:

![Screenshot_20221202-120047](https://user-images.githubusercontent.com/12086466/205278257-2ba299d2-3a9b-4084-b029-403c5e8786bb.png)
![Screenshot_20221202-120051](https://user-images.githubusercontent.com/12086466/205278272-d510a708-a75e-4d17-9e66-e1ae799112da.png)

**Comment by devvv4ever** [comment]
I've tried to simpify it a bit :) After switching the option to "active" a dialog could appear where users can enter the "minutes". After clicking SET the user gets feedback in the supporting text of the switches title.

![image](https://user-images.githubusercontent.com/3578887/205306673-bc4ec5ca-5bae-4023-a53a-324e492e155b.png)

**Comment by ArnyminerZ** [comment]
@devvv4ever okay, I can work on that

**Comment by ArnyminerZ** [comment]
> Wow you're fast ;-) We'd need to re-download the events after the state of the switch is changing.

Yup, I'm working on that. I don't know how you implemented alert disabling in DAVx5. If I remove all alerts with `event.alerts.clear()`, then if the switch to ignore alarms is turned back on, there's any way of recovering this information without re-downloading all the data.

I'm working on a custom property inside of `event.unknownProperties` called something like `ALARMS-BAK`. All the alarms get moved here, removing them from the normal alarms property. Then, if we enable the provider's alarms back again they get extracted from `ALARMS-BAK` and put back into the usual alarms field.

I'm just getting a quite stubborn error for converting a `Trigger` back to the alarm object. Somehow `-PT15M` cannot be parsed to a `Duration`.

**Comment by rfc2822** [comment]
> Yup, I'm working on that. I don't know how you implemented alert disabling in DAVx5. If I remove all alerts with `event.alerts.clear()`, then if the switch to ignore alarms is turned back on, there's any way of recovering this information without re-downloading all the data.

There's no problem with re-downloading the data… I'd add an option to the worker like "don't use cache", and then call the refresh worker without this option when the alarm settings are changed. The option would have to ignore the ETag and Last-Modified headers and then also every VEVENT must be actually written to the calendar.

> I'm working on a custom property inside of `event.unknownProperties` called something like `ALARMS-BAK`. All the alarms get moved here, removing them from the normal alarms property. Then, if we enable the provider's alarms back again they get extracted from `ALARMS-BAK` and put back into the usual alarms field.

We want the subscriptions to be refreshed regulary neverthess, I'd save the work and just trigger a refresh (but without caching)… what do you think about that?

Saving reminders to CAL_SYNC7 and CAL_SYNC8 seems fine to me (I'd also do it like that); that can then be changed with #76.

**Comment by ArnyminerZ** [comment]
@rfc2822 take a look at #78. I believe it's all working correctly 😉
