### ISSUE TITLE
Crash when pressing back button

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#113]
Steps to reproduce:

- Preparation: add a subscription, close ICSx⁵
- Open subscription list
- Edit a subscription (`EditCalendarActivity`)
- Press back button

The app then crashes in the Emulator (Android 12).

I also don't know if we have to add

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU)
            onBackInvokedDispatcher.registerOnBackInvokedCallback(
                OnBackInvokedDispatcher.PRIORITY_DEFAULT,
            ) { handleOnBackPressed() }
        else
            onBackPressedDispatcher.addCallback { handleOnBackPressed() }
```

to every (?) activity, looks a bit much. In doubt I'd just ignore this Android 14 back button thing and keep things as simple as possible.

**Comment by ArnyminerZ** [comment]
We could add it to the other activities as well, but I don't know if it's necessary. We can use the AndroidX library and just have this:
```kotlin
onBackPressedDispatcher.addCallback(object : OnBackPressedCallback(true) {
    override fun handleOnBackPressed() { /* HANDLE BACKPRESS */ }
})
```
Found it in [this](https://codelabs.developers.google.com/handling-gesture-back-navigation#4) codelab.
