### ISSUE TITLE
Generate locales with Locator

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#126]
See https://github.com/bitfireAT/davx5/issues/191

I have just looked in ICSx⁵ app languages and there are multiple entries for "English". I think you have fixed that already but it should be in a lib (submodule if really necessary) and then we can use it for all apps :)

I think we should take the time to make this proper :)

**Comment by ArnyminerZ** [comment]
Yes, it should have been fixed in the last version of Locator. It has still not been released because I'm having some troubles with Gradle's domain verification, but will test ASAP
