### ISSUE TITLE
Provide sync menu entry

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#127]
Currently forcing synchronization is only possible with the swipe-down gesture. However this is

1. not accessible, and
2. users may not know this gesture and that it is used for synchronization.

So we should provide an additional way to force synchronization. I think a menu entry (and maybe a [Small FAB?](https://m3.material.io/components/floating-action-button/guidelines#2f9ec481-b30d-4dc3-89d7-feb2ca7bec4d)) could be appropriate.

**Comment by ArnyminerZ** [comment]
Maybe it's time to start discussing #91. I can start working on a design which would fix this issue, as well as #102 and #14

**Comment by ArnyminerZ** [comment]
Okay, anyway it's not a big deal to add an extra option to the overflow menu, for example

**Comment by ArnyminerZ** [comment]
I have added this "Refresh" menu entry.

![Screenshot_20230227_113507](https://user-images.githubusercontent.com/12086466/221541081-0af2bc3f-347a-41dc-8f55-4bcd4b098ab9.png)
