### ISSUE TITLE
Subscriptions are added back again by migration

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/icsx5#134]
When removing a subscription, it's only removed from the database. When the synchronization runs, the worker sees the calendar on the system, but not the entry in the database, and it considers it as "an old calendar", and migrates it.

This is even worse, since in the conversion from subscription to calendar properties, we don't add `NAME`:
https://github.com/bitfireAT/icsx5/blob/34ab68d0cf82a8107e7f2906510ed62dd1c99da5/app/src/main/java/at/bitfire/icsdroid/db/entity/Subscription.kt#L75-L85

So the system doesn't know the url of the subscription, and just adds them with `https://invalid-url` as specified here:
https://github.com/bitfireAT/icsx5/blob/34ab68d0cf82a8107e7f2906510ed62dd1c99da5/app/src/main/java/at/bitfire/icsdroid/db/entity/Subscription.kt#L61-L63

We should fix the `Subscription` -> `ContentValues` conversion with this:
```kotlin
    /**
     * Converts this subscription's properties to [android.content.ContentValues] that can be
     * passed to the calendar provider in order to create/update the local calendar.
     */
    fun toCalendarProperties() = contentValuesOf(
        Calendars._ID to id,
        Calendars.NAME to url.toString(),
        Calendars.CALENDAR_DISPLAY_NAME to displayName,
        Calendars.CALENDAR_COLOR to color,
        Calendars.CALENDAR_ACCESS_LEVEL to Calendars.CAL_ACCESS_READ,
        Calendars.SYNC_EVENTS to 1
    )
```

Which is fixed here: 3a8452554729b804c831edd624c6b4abb43e9e03

---

For migration, I suggest simply removing this process from synchronization, and moving it to the callback on the database creation:
https://github.com/bitfireAT/icsx5/blob/34ab68d0cf82a8107e7f2906510ed62dd1c99da5/app/src/main/java/at/bitfire/icsdroid/db/AppDatabase.kt#L61-L66

Since I think there are really no reasons to run migration again after the database has been created. This also gets rid of `ONLY_MIGRATE` from the worker, which is a bit specific.

Depends on #133

**Comment by rfc2822** [comment]
Fixed by 606960ee4e7fd128ba75dd021e88b12b2830218b
