### ISSUE TITLE
[Mockup] UI overhaul for setup view

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/icsx5#14]
We should streamline the UI of  to make it more clear for users how they can add subscriptions and with respect to the available options. With the newly added possibility to choose a file from any SAF capable document provider they can choose between two options how to add a subscription. By using tabs they can easily distinguish between these two options. "By URL" should be standard.

Used material icons: "link" and "folder_open".

![grafik](https://user-images.githubusercontent.com/3578887/152142851-4391e6c1-6326-4be5-80db-178d062b12d9.png)

Guidelines: https://material.io/components/tabs#anatomy

**Comment by devvv4ever** [comment]
We'll be implementing the new view when we have more time for not-so-important things ;-) Functionality has been implemented in the 2.0 release.

**Comment by ArnyminerZ** [comment]
Maybe this is a good opportunity for my beloved Jetpack Compose 😄

**Comment by devvv4ever** [comment]
Funnily I just talked about that with @rfc2822 today while sitting in the train ;-) Let's talk about it, soon. This December will be a ICSx5-Love-Month - I can feel it :dancers:

**Comment by ArnyminerZ** [comment]
Regarding this, I'd implement first #76. This way it's easier to display the data from Room, and also we don't have to refractor all the data loading swice.
