### ISSUE TITLE
Provide an option to ignore or set reminders for full-day events separately from other events

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/icsx5#141]
People tend to have events imported that are full-day-events and are internally starting at 12AM. If they set a reminder of 5 minutes they get waked up at 11:55 PM in the night ;-)

real-world issue: https://bitfire-at.zammad.com/#ticket/zoom/376

**Comment by ArnyminerZ** [comment]
Maybe we can add something like this:

![image](https://user-images.githubusercontent.com/12086466/228018115-5b58beda-c1a3-4d83-a498-63260d9c6560.png)

Two different switches for the alarms. I'm not sure how to label them because it might be confusing between "all events" and "all all-day events"
