### ISSUE TITLE
Update to AGP 8.0

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#151]
ICSx5 should be updated to the latest libraries (including our own ones: cert4android, ical4android) and AGP 8.0, too.

Maybe we have to fiddle around with ProGuard; it would be important to generate a signed build (with some dummy key) and see whether it works.

See also what was necessary in DAVx5:

- https://github.com/bitfireAT/davx5/commit/475cc3c7332313b6cfb650256094cb9d8d64ce32
- https://github.com/bitfireAT/davx5/commit/e25209484ca77a01f5ccd4f42a81baade267ddca

So I think these would be the tasks:

- [x] Update gradle to 8.0
- [x] Update AGP to 8.0
- [x] Use Java 17 in the workflows
- [x] Use latest own libraries
- [x] Update dependencies if necessary

**Comment by ArnyminerZ** [comment]
I think this should be ready
