### ISSUE TITLE
Time of shared ISC calendar file is displayed incorrectly (timezone problem)

### ISSUE THREAD

**Issue by BSG2000** [bitfireAT/icsx5#156]
### Discussed in https://github.com/bitfireAT/icsx5/discussions/74

<div type='discussions-op-text'>

<sup>Originally posted by **BSG2000** November 23, 2022</sup>
I have an Exchange calendar in which I share appointments with my girlfriend. Since she only needs read access, we have solved this by sharing the calendar via ICS. Unfortunately, since the last time change, the serial appointments are displayed one hour later (too early). For example, instead of 17:00 in reality, they start at 16:00. Is there any way to fix this? Does anyone know about this problem?

You could provide an offset in the app configuration. That would be a workaround.</div>

Upd: Please read the discussion to get all the information you require.

**Comment by rfc2822** [comment]
The issues are only for confirmed issues where we already know what the exact problem is. For everything else, please use Discussions.
