### ISSUE TITLE
Error notifications

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/icsx5#170]
~Currently we do not show any notification when the synchronization is running, neither when synchronization has failed? (not sure about this one, but I can't find where it's created.)~

~We should provide some notification to tell the user that sync is running, and for notifying about errors as well. We should even show some progress that can be displayed in the UI and notification maybe.~

Show a notification when the synchronization fails.

**Comment by sunkup** [comment]
I agree with you about the failed sync notification. In every other case I would not want to be bothered by the app - that is not show any notification unless something goes wrong. IMHO ICSx5 should, like DAVx5 simply do its job quietly in the background. :) 

For the feedback inside the app - I think the last synced timestamp does suffice. What could be a good use case scenario  with benefits to add the functionality?

**Comment by ArnyminerZ** [comment]
Yup, I agree. I'd stick with #102, and change this one to "add error notification"
