### ISSUE TITLE
Clicking on added calendar subscription crashes app

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/icsx5#191]
I noticed this quite some time ago - if you click on the subscription the app crashes instead of being able to edit the subscription. Here is a video of what happens:

ICSx5 2.2-beta1 on my Samsung S23

https://github.com/bitfireAT/icsx5/assets/3578887/67ff7a33-8a75-44cd-9c6d-a1be69955975

Could someone try to reproduce this and see why it crashes?

**Comment by sunkup** [comment]
Hmm, not reproducible for me :)

**Comment by befocken** [comment]
Also just ran into this problem. Any update concerning this issue?

**Comment by ArnyminerZ** [comment]
Hi, ICSx5 is being reworked from the ground up, and it will take a while. Please, meanwhile use the production version (leave beta). Sorry for the inconveniences.

**Comment by befocken** [comment]
> Hi, ICSx5 is being reworked from the ground up, and it will take a while. Please, meanwhile use the production version (leave beta). Sorry for the inconveniences.

I understand that, thank you for your work.

I just noticed, that the crashes that I experienced can be better explained by the ticket #185... 🤔 I have version 2.1.1 installed, not the beta version.

**Comment by Brog33** [comment]
The same happens to me too

**Comment by ArnyminerZ** [comment]
Solved on the last beta (Compose migration).
