### ISSUE TITLE
Android 11: move from file URIs to SAF

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#2]
Since Android 10, file URIs shouldn't/can't access files outside the own application anymore. Since Android 11, file URIs for shared files are possible again, but the better method is SAF and content URIs.

So ICSx⁵  should support SAF instead of file:// URIs.

**Comment by rfc2822** [comment]
Real-life use case:

>Yes, of course. As I wrote below, I have an ICS file that is kept up to date on my phone (a Fairphone 2 running Lineage OS) using Syncthing from https://f-droid.org/packages/com.nutomic.syncthingandroid/
>
>The file itself is placed in /storage/emulated/0/SomeFolder/File.ics (The /storage/emulate/0 folder is also available as /sdcard as far as I understand, but it is internal storage.)
>
>The folder "SomeFolder" is synchronized using SyncThing, but it is also read and writable from other apps with "manage all files" permission (for example in Termux) or when using a file-picker/intent.
>
>According to this FAQ Syncthing cannot write to external SD cards:
>https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions
>
>So overall if the content:// URL or SAF can pick up a file somewhere in the general internal storage then it should work for 
my use case I think.

**Comment by hiqua** [comment]
I have the same use-case, Android 11 as well, so to make it work I have to use a version patched with:
```
diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 8c0c897..d319a7e 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -15,6 +15,7 @@
         android:maxSdkVersion="22" />
     <!-- add/update/delete events -->
     <uses-permission android:name="android.permission.READ_CALENDAR" />
+    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
     <uses-permission android:name="android.permission.WRITE_CALENDAR" />
     <!-- view/change the sync interval and whether the account is synchronizing -->
     <uses-permission android:name="android.permission.READ_SYNC_SETTINGS" />
@@ -39,6 +40,7 @@
         android:name=".MyApp"
         android:networkSecurityConfig="@xml/network_security"
         android:requestLegacyExternalStorage="true"
+        android:preserveLegacyExternalStorage="true"
         android:theme="@style/AppTheme"
         tools:ignore="UnusedAttribute">
 
@@ -158,4 +160,4 @@
             android:parentActivityName=".ui.CalendarListActivity" />
     </application>
 
-</manifest>
\ No newline at end of file
+</manifest>
```

**Comment by rfc2822** [comment]
Thanks, but that still uses the legacy way, which won't be supported in the next Android versions anymore.

**Comment by hiqua** [comment]
Yup of course, it's just a work-around for Android 11, since it just doesn't work at all otherwise.

**Comment by rfc2822** [comment]
@hiqua May I ask for your use case too? Which local files do you synchronize with and why?

**Comment by hiqua** [comment]
Exactly the same as https://github.com/bitfireAT/icsx5/issues/2#issuecomment-987796051

**Comment by megies** [comment]
On Android 11, icsx5 `v1.9.4-standard`, I try to subscribe to a local calendar via `file:///storage/emulated/0/...../some_file.ics` that is synced by a 3rd party App (it's a new phone, I did it like that on older Android before). I get an error message `/storage/emulated/0/.../some_file.ics: open failed: EACCES (Permission denied)`.
I've tried to give icsx5 more file permissions, but it seems to not be possible to give more extensive file permissions than requested by the app.

It sounds like this ticket is about that problem and it should already be fixed in `dev` branch, with that related PR merged already? So that use case will be fixed when https://github.com/bitfireAT/icsx5/milestone/1 will get released?

**Comment by rfc2822** [comment]
> So that use case will be fixed when https://github.com/bitfireAT/icsx5/milestone/1 will get released?

Exactly. It should be released soon :)

**Comment by megies** [comment]
Awesome, thanks a lot for the confirmation! :rocket:

**Comment by megies** [comment]
Works like a charm, thanks!
