### ISSUE TITLE
Unable to Resolve Host

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/icsx5#215]
Find why it happens, and solve it.

Reported in #73

**Comment by ArnyminerZ** [comment]
I think we should always ask to disable battery optimization. As far as I have found out, it's most of the times problematic with network fetches on the background.

**Comment by ArnyminerZ** [comment]
I've been using this fix for two days (disabling battery optimization) and I've not had the DNS issue again (which I used to have daily)

**Comment by sunkup** [comment]
> I've been using this fix for two days (disabling battery optimization) and I've not had the DNS issue again (which I used to have daily)

@ArnyminerZ Is it still working fine for you? :)

**Comment by ArnyminerZ** [comment]
> @ArnyminerZ Is it still working fine for you? :)

No issues so far, works well. I haven't received the error again

**Comment by sunkup** [comment]
Ok, will merge then. :+1:
