### ISSUE TITLE
Progress sync animation running forever if permissions never granted

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/icsx5#236]
Just found a minor thing:

* Freshly install ICSx5 2.2-beta2
* Don't grant permissions
* Add a subscription
* Try to sync

Result: Progress animation is running forever (see screenshot)

Expected: Progress bar should disappear shortly after recognized that no sync is possible due to missing permissions. Alternatively the progress bar could simply be not shown at all when there are missing permissions

![grafik](https://github.com/bitfireAT/icsx5/assets/3578887/f226ee18-9b40-4258-b973-ce185d42d903)

**Comment by ArnyminerZ** [comment]
I can't manage to reproduce, works fine for me :(

**Comment by ArnyminerZ** [comment]
Can you try the latest dev version? Instead of the published one, directly from the dev branch

**Comment by devvv4ever** [comment]
I can't build it on my own, since I don't have any Studio installed :-/ Is there a re-compiled version from master anywhere that I miss? If no you can send it to me and I'll try on that device.

**Comment by ArnyminerZ** [comment]
Sorry for the late answer, here's a compiled version, the one I checked with and seemed to work fine

https://cloud.bitfire.at/s/sDMFYBo4rWX8NwR

**Comment by devvv4ever** [comment]
Seems to work with 2.2, or at least couldn't reproduce anymore :D
