### ISSUE TITLE
Simplify UI

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/icsx5#270]
We should really simplify the UI of the app, at least card-wise. This is the first thing you see when first installing the app:

![image](https://github.com/bitfireAT/icsx5/assets/12086466/15b10b7d-e552-424c-bf6f-58be2f95d0ca)

I think it's a bit overwhelming.

**Comment by sunkup** [comment]
True, any ideas other than an app intro?

**Comment by ArnyminerZ** [comment]
I have two proposals, I don't love them, but I think that at least they use less space

| Current | Proposal A | Proposal B |
|---|---|---|
| ![icsx5-cards-old](https://github.com/user-attachments/assets/8d9264d3-0ed5-485a-98f5-2ea93795b3a6) | ![icsx5-cards-grid](https://github.com/user-attachments/assets/c5afd844-7d89-4822-9ea0-3d7b0644261b)  | ![icsx5-cards-icons](https://github.com/user-attachments/assets/5fe2056d-6b7c-4b0e-855c-e92c59b89a31) |

**Comment by sunkup** [comment]
Oh, nice!

I would go with B or C and make the whole card clickable. :)

**Comment by ArnyminerZ** [comment]
Bernhard likes C, we can make the whole card clickable on either case
