### ISSUE TITLE
[Severe] Can't save edits

### ISSUE THREAD

**Issue by sunkup** [bitfireAT/icsx5#308]
Try editing a subscription. The save icon appears, but when you tap it, nothing happens. 
Saving with the dialog that opens when you try to leave the screen, does not seem to work either.

**Comment by ArnyminerZ** [comment]
I think it's saving, but the UI isn't receiving the update. May be caused by the updates in #287

**Comment by ArnyminerZ** [comment]
Yes, this is not actually an issue but #309

**Comment by ArnyminerZ** [comment]
Superseded by #309
