### ISSUE TITLE
Get calendar color when at subscription

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#31]
Calendars (Webcal feeds) can contain a color that shall be used for the whole calendar.

Possible representation:

* `COLOR` (RFC 7986)
* `X-APPLE-CALENDAR-COLOR`, see https://github.com/bitfireAT/icsx5/discussions/29#discussioncomment-2328294

This color could be used as a suggestion when adding a calendar.

- [ ] `ResourceInfo`: add `calendarColor` like `calendarName`
- [ ] `AddCalendarValidationFragment.ValidationModel`: get calendar color like calendar name
- [ ] `AddCalendarValidationFragment`: set initial color from calendar color (fall back to lightblue)

**Comment by sunkup** [comment]
Should we add fallback support for `X-APPLE-COLOR` too?

**Comment by rfc2822** [comment]
> Should we add fallback support for `X-APPLE-COLOR` too?

I don't think this is necesary; I haven't seen `X-APPLE-COLOR` yet. The standard way is `COLOR` (but I doubt anyone is already using it); currently `X-APPLE-COLOR` is used.

Maybe the parsing of `COLOR` should understand hex values, too, although they're not allowed in the standard. I guess as soon as `COLOR` is used more widely, people will use it for hex values. But this is perhaps better off in another issue :)

**Comment by cwchristerw** [comment]
> @rfc2822 Maybe the parsing of COLOR should understand hex values, too, although they're not allowed in the standard.
https://www.w3.org/TR/css-color-3/

**Comment by rfc2822** [comment]
[RFC 7986 says](https://datatracker.ietf.org/doc/html/rfc7986#section-5.9):

> The value is a case-insensitive color name taken from the CSS3 set of names, defined in Section 4.3 of [[W3C.REC-css3-color-20110607](https://datatracker.ietf.org/doc/html/rfc7986#ref-W3C.REC-css3-color-20110607)].

Maybe parsing hex values would be good for compatibility, but nevertheless they're invalid for `COLOR`.

**Comment by cwchristerw** [comment]
I read too late removed my comment :smile:

**Comment by cwchristerw** [comment]
Its good idea to add support for HEX colors also just in case :smile:
