### ISSUE TITLE
Adapted auto-revoke of permissions text for android versions

### ISSUE THREAD

**Issue by sunkup** [bitfireAT/icsx5#353]
The user is told to disable auto-revoke of permissions.
<details>

![image](https://github.com/bitfireAT/icsx5/assets/8227414/8fa09f77-ba46-4a48-9be6-f050a6f754a3)

</details>

In different android versions this has different names. In android 14 it is called "Pause app activity if unused". This is hard for the user to find if told to disable auto-revoke of permissions. We should adapt the popup accordingly to android versions.

<details>

![image](https://github.com/bitfireAT/icsx5/assets/8227414/591c6e6b-739a-4f19-8d69-4c42072b2cf7)

</details>

**Comment by ArnyminerZ** [comment]
I think it's pretty hard to know how it's called on all the different versions, because even different ROMs may vary this. Do you know if there's any list or something?

**Comment by sunkup** [comment]
> I think it's pretty hard to know how it's called on all the different versions, because even different ROMs may vary this. Do you know if there's any list or something?

hmm, yes maybe you are right. No, I don't have a list. Maybe we can leave it as is until ICSx5 is merged into DAVx5 later this year. :)
