### ISSUE TITLE
Donation dialog does not show button on standard

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/icsx5#370]
The ose version of ICSx5 shows a donation dialog every once in a while, which does have a correct working donation button, but once you hide it, it doesn't pop up again, and can't be invoked in any other way. If the one in the info activity is pressed, the same is shown both in gplay and standard, which doesn't contain any donation button to comply with Google Play's policy.

This dialog should be the same as the one that pops up automatically in standard.

**Comment by ArnyminerZ** [comment]
Actually, according to the new [Google Play's Policy to comply the DMA in EEA](https://support.google.com/googleplay/android-developer/answer/10281818?sjid=16339611449746232021-EU#DMA_EEA&zippy=%2Chow-has-the-digital-markets-act-dma-impacted-google-plays-payments-policy-for-users-in-the-european-economic-area-eea) does allow external donation links:

> Additionally, developers may lead users in the EEA outside of the app, including to promote offers for in-app digital features and services, subject to [program requirements](https://support.google.com/googleplay/android-developer/answer/14372887).

However, I don't think it matters that much, since I don't think we really need to have a new flavor for EEA users.

**Comment by stefan2904** [comment]
Interesting. How are apps like Signal doing this? They also have a working donation system in their gplay version.

**Comment by ArnyminerZ** [comment]
I'm not sure how Signal deals with it, but most apps use a "virtual buy" system. This is, buying things like "a coffee", "cinema tickets"... In DAVx5 we have virtual badges for example.
