### ISSUE TITLE
Update documentation about adding calendars via https URLs

### ISSUE THREAD

**Issue by sunkup** [bitfireAT/icsx5#379]
Opening a http(s) URL for an .ics file in the browser does not redirect to ICSx5 anymore. webcal(s) URLs do still work though.

See the details in https://github.com/bitfireAT/icsx5/issues/246#issuecomment-1997929511

We should update the [website documentation](https://icsx5.bitfire.at/usage/#setup) (Setup and QR Code sections) that http(s) URL's are not supported any more. 

@devvv4ever Can you do that for us?

**Comment by devvv4ever** [comment]
Is it not possible anymore on a technical level?

The website is a github repo: https://github.com/bitfireAT/icsx5-website So you should be able to modify it at anytime to reflect the current capabilities of the app.

**Comment by sunkup** [comment]
> Is it not possible anymore on a technical level?

I did not check the details, but according tot @ArnyminerZ it's not possible anymore.

**Comment by devvv4ever** [comment]
I commited the changes but it has yet to be built again so that it becomes visible.

**Comment by ArnyminerZ** [comment]
> Is it not possible anymore on a technical level?

I think it's _technically_ possible, if the user manually enters the URL in the app's configuration in settings, but I think not all OEMs allow that, and it's quite strange to add, so I wouldn't even consider it as "supported".

**Comment by ArnyminerZ** [comment]
I'd say this issue is solved in https://icsx5.bitfire.at/usage/ right?
