### ISSUE TITLE
Add icon.png to metadata en-US images

### ISSUE THREAD

**Issue by licaon-kter** [bitfireAT/icsx5#391]

**Comment by ArnyminerZ** [comment]
Please, add a description to the issue, or explain better what you mean, otherwise we can't do much.

**Comment by licaon-kter** [comment]
per https://gitlab.com/-/snippets/1895688#structure you need to add `icon.png` to https://github.com/bitfireAT/icsx5/tree/dev/fastlane/metadata/android/en-US `images/` folder so the icon is shown on F-Droid website ( https://f-droid.org/packages/at.bitfire.icsdroid/ ) and in F-Droid clients
