### ISSUE TITLE
Android 12 compatibility

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#5]
- [ ] Make ICSx⁵ compatible with Android 12
- [ ] Test with Android 12, especially Android 12-specific things

If there are problems, please track here.

**Comment by sunkup** [comment]
Problems
- [ ] [ForegroundServiceStartNotAllowedException](https://developer.android.com/guide/components/foreground-services#background-start-restrictions), turning off battery optimization does **not** seem to help  
- [ ] Toast messages fail to [load application icon](https://developer.android.com/about/versions/12/behavior-changes-12#toast-redesign)
