### ISSUE TITLE
Android 13 compatibility

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#77]
Raise target level to Android 13

- [x] handle notification permission ([docs](https://developer.android.com/develop/ui/views/notifications/notification-permission))
- [x] predictive back gesture ([docs](https://developer.android.com/guide/navigation/predictive-back-gesture))
  - [x] Update `androidx.appcompat:appcompat` to `1.6.0-rc01` ([Release notes](https://developer.android.com/jetpack/androidx/releases/appcompat#version_160_2))
- [x] per-app language preferences ([docs](https://developer.android.com/guide/topics/resources/app-languages))
- [x] themed icon (monochrome) ([docs](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive))
- [ ] check whether anything else has changed
- [x] update libraries and dependencies
  - [x] Update AGP to `7.3.1`
    - [x] Move package from Android manifest to build files ([see](https://stackoverflow.com/a/72226799))
    - [x] Update desugaring lib to `1.2.0` ([docs](https://developer.android.com/studio/write/java8-support#library-desugaring-versions))
  - [x] Update Kotlin to `1.7.20`
  - [x] Update `androidx.test.runner` to `1.5.0` (no breaking changes - [Release notes](https://developer.android.com/jetpack/androidx/releases/test#runner_150_2))
  - [x] Update `androidx.test:rules` to `1.5.0` (no breaking changes - [Release notes](https://developer.android.com/jetpack/androidx/releases/test#runner_150_2))
  - [x] Update `com.google.android.material:material` to `1.7.0` ([Release notes](https://github.com/material-components/material-components-android/releases/tag/1.7.0))
    - [x] Requirement of AGP `>=7.2.0` (we are using `7.2.2` -> `7.3.1`)
    - [x] Requirement of Gradle `>=7.3.3` (we are using `7.4.2`)
    - [x] Requirement of Java 8
  - [x] Update `androidx.core:core-ktx` to `1.9.0` ([Release notes](https://developer.android.com/jetpack/androidx/releases/core#1.9.0) - Improves compatibility with Android 13)
  - [x] Update `androidx.fragment:fragment-ktx` to `1.5.4` ([Release notes](https://developer.android.com/jetpack/androidx/releases/fragment#1.5.4) - Just bugfixes)
- [x] raise target level (`targetSdkVersion`) to `33`
- [x] raise compile level (`compileSdkVersion`) to `33` and build tools (`buildToolsVersion`) to `33.0.0`

**Comment by ArnyminerZ** [comment]
I might be missing something, but I believe this is all

**Comment by ArnyminerZ** [comment]
We should choose how we ask the notifications permission. Just ask for it, like the calendar access, or show a message?
@rfc2822 @devvv4ever

**Comment by ArnyminerZ** [comment]
I've opened #79 with all the changes. It's just missing to decide something for the themed app icon, since the current one clearly cannot be themed. And just check if there's anything missing.

**Comment by devvv4ever** [comment]
Didn't work on our logos for a long time, but I hope this is sufficient for a monochrome version. Can you use this?

![ICS-droid-monochrome-2022-1-minified](https://user-images.githubusercontent.com/3578887/206230026-819e52ef-ed44-4b58-911b-a94963c3f8fe.svg)

**Comment by ArnyminerZ** [comment]
Mmmmh... I can try it out

**Comment by ArnyminerZ** [comment]
Well, I had to tweak it a little bit so it was pure monochrome

![icsx5](https://user-images.githubusercontent.com/12086466/206309995-ab891b18-6cf1-442d-956a-a3f2c6ec122e.svg)

It's a quite detailed logo for being so small, but I think it looks quite fine

![Screenshot_20221207-232526](https://user-images.githubusercontent.com/12086466/206310386-63004f5f-1448-4d7a-93c5-5d2b2a98a82f.png)

**Comment by devvv4ever** [comment]
Looks cool, lets use it :)
