### ISSUE TITLE
Credentials should be stored in `EncryptedSharedPreferences`

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/icsx5#95]
Right now, credentials are being stored inside regular `SharedPreferences` in `CalendarCredentials`:
https://github.com/bitfireAT/icsx5/blob/0b1443de38e0e32f147351ae36358c01af710236/app/src/main/java/at/bitfire/icsdroid/db/CalendarCredentials.kt#L17-L19

[`EncryptedSharedPreferences`](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) shall be used.

The change is quite simple, they provide a good example:
```kotlin
MasterKey masterKey = new MasterKey.Builder(context)
     .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
     .build();

 SharedPreferences sharedPreferences = EncryptedSharedPreferences.create(
     context,
     "secret_shared_prefs",
     masterKey,
     EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
     EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
 );

 // use the shared preferences and editor as you normally would
 SharedPreferences.Editor editor = sharedPreferences.edit();
```

**Comment by ArnyminerZ** [comment]
Note the warning on the docs:

> The preference file should not be backed up with Auto Backup. When restoring the file it is likely the key used to encrypt it will no longer be present. You should exclude all `EncryptedSharedPreference`s from backup using [backup rules](https://developer.android.com/guide/topics/data/autobackup#IncludingFiles).

This means that we should provide an option to authorize back again after a device factory reset, or backup restore. Should be taken into account with #4.

Also `security-crypto` shall be added as dependency:
```groovy
implementation "androidx.security:security-crypto:1.0.0"
```

**Comment by rfc2822** [comment]
When we have the database, I'd just store everything (including credentials) in the private DB. EncryptedSharedPreferences says that it doesn't work across system backup/restore on different devices, but this is a use case that is planned (#4).

Unfortunately we have to store the credentials in clear text for Basic authentication.

**Comment by ArnyminerZ** [comment]
Then we should store the accounts in Room instead of shared preferences for #76. This means creating a new table, and getting rid of [`CalendarCredentials`](https://github.com/bitfireAT/icsx5/blob/database/app/src/main/java/at/bitfire/icsdroid/db/CalendarCredentials.kt).

**Comment by rfc2822** [comment]
> Then we should store the accounts in Room instead of shared preferences for #76. This means creating a new table, and getting rid of [`CalendarCredentials`](https://github.com/bitfireAT/icsx5/blob/database/app/src/main/java/at/bitfire/icsdroid/db/CalendarCredentials.kt).

Sounds reasonable :)
